name: BUtilsSupport
version: ${project.version}
main: de.butilsfaq.butilssupport.BUtilsSupport
api-version: 1.16
depend: [ BUtils ]
authors: [ Maximilian1021, l4zs ]
description: BUtils Support
website: https://www.butils-faq.de

commands:
  data:
    description: Gibt dem Support wichtige Daten von deinem Server!